[terminal]
show_terminal_zero_state_block = false

[terminal.input]
input_box_type_setting = "universal"
honor_ps1 = false

[agents]
cloud_conversation_storage_enabled = true

[agents.warp_agent]
is_any_ai_enabled = true

[agents.warp_agent.input]
nld_in_terminal_enabled = false

[agents.warp_agent.other]
show_agent_notifications = true
show_conversation_history = true
should_render_use_agent_toolbar_for_user_commands = false

[agents.third_party]
should_render_cli_agent_toolbar = true

[account]
is_settings_sync_enabled = true

[privacy]
telemetry_enabled = true
crash_reporting_enabled = true

[general]
default_session_mode = "terminal"
show_warning_before_quitting = false
login_item = false

[appearance]

[appearance.vertical_tabs]
enabled = false

[appearance.window]
override_opacity = 75
override_blur = 20

[appearance.text]
notebook_font_size = 14.0
font_size = 13.0
font_name = "MesloLGS Nerd Font Mono"
ai_font_name = "MesloLGS Nerd Font Mono"
match_ai_font = false

[appearance.themes]
theme = { custom = { name = "Duskhaven", path = "duskhaven.yaml" } }

[appearance.icon]
app_icon = "default"

[code]

[code.editor]
show_code_review_button = true
show_project_explorer = true
show_global_search = true

[warp_drive]
enabled = true

[warpify]

[warpify.ssh]
enable_ssh_warpification = false

[notifications]
toast_duration_secs = 8

[notifications.preferences]
is_agent_task_completed_enabled = true
is_long_running_enabled = true
is_needs_attention_enabled = true
is_password_prompt_enabled = true
long_running_threshold = 30
mode = "dismissed"
play_notification_sound = true
