set -g default-terminal "tmux-256color"

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

set -g mouse on

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'

# tmux-plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin 'egel/tmux-gruvbox'
set -g @plugin 'catppuccin/tmux#v2.1.3' # See https://github.com/catppuccin/tmux/tags for additional tags

# gruvbox settings
set -g @tmux-gruvbox 'dark'
set -g @tmux-gruvbox-right-status-x '%m/%d/%Y' # e.g.: 01/31/2024
set -g @tmux-gruvbox-right-status-y '%I:%M %p' # 09:54 PM

# catppuccin settings
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

# run ~/.tmux/plugins/tmux/catppuccin.tmux

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"

# Initialize TMUX plugin manager (key this line at very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
